### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by cathywilkie** [cathywilkie/animal-rescue-website#2]
My website have showcase transformation and transition (on the rescue cards) and the homepage banner was saved for web as learned this semester. I used svg when possible, prepared as learned too.

I struggled with everything this semester, but mostly time. This website is nowhere near done, in both design and accessibility/performance. I still need to change the placeholders and fix colour issue. (and as you can see I don't have the google doc ready for the testing.) 

I would give myself a C, or lower. But considering many student didn't even try to do the last assignment, I am proud to submit something.

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
